apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    name: myapp
    business: front-end
    os: captial-markets
    env: production
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: "nginx"
          resources:
            limits:
            memory: "256Mi"
            cpu: "500m"
          ports:
            - containerPort: 80

        
